### PR TITLE
Add missing :query action

### PR DESCRIPTION
**Pull request by ajkerr**
This pull request addresses #118.

### CODE REVIEW

**Comment by fishnix** [comment]
@ajkerr When using your branch and something like:

```ruby
mysql_connection_info = {
  :host     => '127.0.0.1',
  :username => 'root',
  :password => node['mysql']['server_root_password']
}

mysql_database 'run script' do
  connection mysql_connection_info
  sql { ::File.open('/tmp/myawesome.sql').read }
  action :query
end
```

I end up with : 

```       
       
             
             ================================================================================
             Error executing action `install` on resource 'mysql2_chef_gem[default]'
             ================================================================================
             
             NoMethodError
             -------------
             undefined method `version' for Chef::Resource::MysqlClient
             
             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:17:in `block (2 levels) in <class:Mysql>'
             /tmp/kitchen/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:16:in `block in <class:Mysql>'
             /tmp/kitchen/cache/cookbooks/database/libraries/provider_database_mysql.rb:104:in `block in <class:Mysql>'
             
             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/database/libraries/provider_database_mysql.rb
             
             102:           mysql2_chef_gem 'default' do
             103:             client_version node['mysql']['version'] if node['mysql'] && node['mysql']['version']
             104:           end.run_action(:install)
             105: 
             106:           begin
             107:             query_sql = new_resource.sql
             108:             Chef::Log.debug("Performing query [#{query_sql}]")
             109:             query_client.query(query_sql)
             110:           ensure
             111:             close_query_client
             112:           end
             113:         end
             
             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/database/libraries/provider_database_mysql.rb:102:in `block in <class:Mysql>'
             
             mysql2_chef_gem("default") do
        action :install
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :mysql2_chef_gem
        cookbook_name "np-jenkins"
             end
             
           
           ================================================================================
           Error executing action `query` on resource 'mysql_database[run script]'
           ================================================================================
           
           NoMethodError
           -------------
           mysql2_chef_gem[default] (/tmp/kitchen/cache/cookbooks/database/libraries/provider_database_mysql.rb line 102) had an error: NoMethodError: undefined method `version' for Chef::Resource::MysqlClient
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:17:in `block (2 levels) in <class:Mysql>'
           /tmp/kitchen/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:16:in `block in <class:Mysql>'
           /tmp/kitchen/cache/cookbooks/database/libraries/provider_database_mysql.rb:104:in `block in <class:Mysql>'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/np-jenkins/recipes/slave.rb
           
            27: mysql_database 'run script' do
            28:   connection mysql_connection_info
            29:   sql { ::File.open('/tmp/myawesome.sql').read }
            30:   action :query
            31: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/np-jenkins/recipes/slave.rb:27:in `from_file'
           
           mysql_database("run script") do
             provider Chef::Provider::Database::Mysql
             action [:query]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             database_name "run script"
             declared_type :mysql_database
             cookbook_name "np-jenkins"
             recipe_name "slave"
             connection {:host=>"127.0.0.1", :username=>"root", :password=>"xxxxxxxx"}
             sql #<Proc:0x000000067e4f90@/tmp/kitchen/cache/cookbooks/np-jenkins/recipes/slave.rb:29>
           end
           
```

**Comment by ajkerr** [comment]
@fishnix Make sure that you have include_recipe "database::mysql" in your cookbook, and that your metadata.rb file explicitly has a dependency on the database cookbook.  This cookbook doesn't work properly without this.

**Comment by fishnix** [comment]
With:

```
node.set['mysql']['version'] = '5.6'
include_recipe 'database::mysql'

mysql_connection_info = {
  :host     => '127.0.0.1',
  :username => 'root',
  :password => node['mysql']['server_root_password']
}

mysql_database 'run script' do
  connection mysql_connection_info
  sql { ::File.open('/tmp/myawesome.sql').read }
  action :query
end
```

I get the same thing:

```
       Recipe: database::mysql
       
           
           ================================================================================
           Error executing action `install` on resource 'mysql2_chef_gem[default]'
           ================================================================================
           
           NoMethodError
           -------------
           undefined method `version' for Chef::Resource::MysqlClient
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:17:in `block (2 levels) in <class:Mysql>'
           /tmp/kitchen/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:16:in `block in <class:Mysql>'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/database/recipes/mysql.rb
           
             2: mysql2_chef_gem 'default' do
             3:   client_version node['mysql']['version'] if node['mysql']
             4:   action :install
             5: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/database/recipes/mysql.rb:2:in `from_file'
           
           mysql2_chef_gem("default") do
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :mysql2_chef_gem
             cookbook_name "database"
             recipe_name "mysql"
             client_version "5.6"
           end        
```

**Comment by ajkerr** [comment]
Did you add the database dependency to your metadata.rb file?

**Comment by ajkerr** [comment]
Also - take a look at #124.  It may help you.

**Comment by fishnix** [comment]
yeah @ajkerr sorry I didnt mention it - 

```
depends 'database', '~> 3.0.3'
```

**Comment by kisoku** [comment]
@ajkerr, have you signed the CLA yet ? I would like to merge this but I'm not seeing a tag from currybot here.

**Comment by kisoku** [comment]
@ajkerr ok I see that you have signed the CLA. I'm going to try and validate this stuff asap

**Comment by kisoku** [comment]
I'm merging this as part of an effort to sort out all of the fallout of mysql 6 cookbook

**Pull request merged**
